#!/bin/bash

for linea in `cat control.txt`;
do
	variable=$(echo $linea | cut -d "." -f 1)
	sed -i 's/HE/He/g' $variable.cif
	sed -i 's/LI/Li/g' $variable.cif
	sed -i 's/BE/Be/g' $variable.cif
	sed -i 's/NE/Ne/g' $variable.cif
	sed -i 's/NA/Na/g' $variable.cif
	sed -i 's/MG/Mg/g' $variable.cif
	sed -i 's/AL/Al/g' $variable.cif
	sed -i 's/SI/Si/g' $variable.cif
	sed -i 's/CL/Cl/g' $variable.cif
	sed -i 's/AR/Ar/g' $variable.cif
	sed -i 's/CA/Ca/g' $variable.cif
	sed -i 's/SC/Sc/g' $variable.cif
	sed -i 's/TI/Ti/g' $variable.cif
	sed -i 's/CR/Cr/g' $variable.cif
	sed -i 's/MN/Mn/g' $variable.cif
	sed -i 's/FE/Fe/g' $variable.cif
	sed -i 's/CO/Co/g' $variable.cif
	sed -i 's/NI/Ni/g' $variable.cif
	sed -i 's/CU/Cu/g' $variable.cif
	sed -i 's/ZN/Zn/g' $variable.cif
	sed -i 's/GA/Ga/g' $variable.cif
	sed -i 's/GE/Ge/g' $variable.cif
	sed -i 's/AS/As/g' $variable.cif
	sed -i 's/SE/Se/g' $variable.cif
	sed -i 's/BR/Br/g' $variable.cif
	sed -i 's/KR/Kr/g' $variable.cif
	sed -i 's/RB/Rb/g' $variable.cif
	sed -i 's/SR/Sr/g' $variable.cif
	sed -i 's/ZR/Zr/g' $variable.cif
	sed -i 's/NB/Nb/g' $variable.cif
	sed -i 's/MO/Mo/g' $variable.cif
	sed -i 's/TC/Tc/g' $variable.cif
	sed -i 's/RU/Ru/g' $variable.cif
	sed -i 's/RH/Rh/g' $variable.cif
	sed -i 's/PD/Pd/g' $variable.cif
	sed -i 's/AG/Ag/g' $variable.cif
	sed -i 's/CD/Cd/g' $variable.cif
	sed -i 's/IN/In/g' $variable.cif
	sed -i 's/SN/Sn/g' $variable.cif
	sed -i 's/SB/Sb/g' $variable.cif
	sed -i 's/TE/Te/g' $variable.cif
	sed -i 's/XE/Xe/g' $variable.cif
	sed -i 's/CS/Cs/g' $variable.cif
	sed -i 's/BA/Ba/g' $variable.cif
	sed -i 's/LA/La/g' $variable.cif
	sed -i 's/CE/Ce/g' $variable.cif
	sed -i 's/PR/Pr/g' $variable.cif
	sed -i 's/ND/Nd/g' $variable.cif
	sed -i 's/PM/Pm/g' $variable.cif
	sed -i 's/SM/Sm/g' $variable.cif
	sed -i 's/EU/Eu/g' $variable.cif
	sed -i 's/GD/Gd/g' $variable.cif
	sed -i 's/TB/Tb/g' $variable.cif
	sed -i 's/DY/Dy/g' $variable.cif
	sed -i 's/HO/Ho/g' $variable.cif
	sed -i 's/ER/Er/g' $variable.cif
	sed -i 's/TM/Tm/g' $variable.cif
	sed -i 's/YB/Yb/g' $variable.cif
	sed -i 's/LU/Lu/g' $variable.cif
	sed -i 's/HF/Hf/g' $variable.cif
	sed -i 's/TA/Ta/g' $variable.cif
	sed -i 's/RE/Re/g' $variable.cif
	sed -i 's/OS/Os/g' $variable.cif
	sed -i 's/IR/Ir/g' $variable.cif
	sed -i 's/PT/Pt/g' $variable.cif
	sed -i 's/AU/Au/g' $variable.cif
	sed -i 's/HG/Hg/g' $variable.cif
	sed -i 's/TL/Tl/g' $variable.cif
	sed -i 's/PB/Pb/g' $variable.cif
	sed -i 's/BI/Bi/g' $variable.cif
	sed -i 's/PO/Po/g' $variable.cif
	sed -i 's/AT/At/g' $variable.cif
	sed -i 's/RN/Rn/g' $variable.cif
	sed -i 's/FR/Fr/g' $variable.cif
	sed -i 's/RA/Ra/g' $variable.cif
	sed -i 's/AC/Ac/g' $variable.cif
	sed -i 's/TH/Th/g' $variable.cif
	sed -i 's/PA/Pa/g' $variable.cif
done
 
